# Generated by Django 5.1.4 on 2025-01-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_usuario_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('names', models.CharField(max_length=50)),
                ('surenames', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=20)),
                ('fono', models.CharField(max_length=10)),
            ],
        ),
    ]
