# Generated by Django 5.1.4 on 2025-01-23 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoCLinicoConocido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion_tema', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('uso_del_tiempo', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('aspectos_semiologicos', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('anamnesis', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('evaluacion_kinesica', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('diagnostico_kinesico', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('condicion_salud_contexto', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('problematica_usuario', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('relacion_evaluacion_razonamiento', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('objetivo_general', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('objetivos_especificos', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('objetivos_operacionales', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('propuesta_tratamiento_contexto', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('educacion_comunidad', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('trabajo_equipo_derivacion', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('pronostico_funcional', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('defensa_caso_clinico', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CasoClinicoDesconocido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion_personal_autocuidado', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('presentacion_tema_capacidad_sintesis', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('uso_del_tiempo', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('seguridad_empatia', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('anamnesis', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('evaluacion_kinesica', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('destreza_evaluacion_kinesica', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('problematica_usuario', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('diagnostico_kinesico', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('relacion_evaluacion_razonamiento', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('objetivo_general', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('objetivos_especificos', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('objetivos_operacionales', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('destreza_tecnicas_kinesicas', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('pronostico_funcional', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
                ('defensa_caso_clinico', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], default='Deficiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Internado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_rotativa', models.IntegerField()),
                ('lugar', models.CharField(max_length=100)),
                ('profesor_guia', models.CharField(max_length=50)),
                ('caso_clinico_conocido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rubricas.casoclinicoconocido')),
                ('caso_clinico_desconocido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rubricas.casoclinicodesconocido')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.estudiante')),
            ],
        ),
    ]
