# Generated by Django 5.1.4 on 2025-01-24 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubricas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internado',
            name='caso_clinico_conocido',
        ),
        migrations.RemoveField(
            model_name='internado',
            name='caso_clinico_desconocido',
        ),
        migrations.AddField(
            model_name='casoclinicoconocido',
            name='internado',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='rubricas.internado'),
        ),
        migrations.AddField(
            model_name='casoclinicodesconocido',
            name='internado',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='rubricas.internado'),
        ),
        migrations.AlterField(
            model_name='internado',
            name='lugar',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='internado',
            name='profesor_guia',
            field=models.CharField(default='', max_length=50),
        ),
    ]
