# Generated by Django 5.1.4 on 2025-01-31 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_estudiante'),
        ('rubricas', '0002_remove_internado_caso_clinico_conocido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casoclinicoconocido',
            name='evaluador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='main.usuario'),
        ),
        migrations.AddField(
            model_name='casoclinicodesconocido',
            name='evaluador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='main.usuario'),
        ),
        migrations.AlterField(
            model_name='casoclinicoconocido',
            name='internado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='rubricas.internado'),
        ),
    ]
