# Generated by Django 5.1.4 on 2025-01-31 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubricas', '0003_casoclinicoconocido_evaluador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casoclinicoconocido',
            name='internado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rubricas.internado'),
        ),
    ]
