# Generated by Django 5.1.4 on 2025-01-31 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubricas', '0004_alter_casoclinicoconocido_internado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casoclinicoconocido',
            name='internado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rubricas.internado'),
        ),
    ]
